---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: community-service
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: community-service
  targetNamespace: default

