---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: community-service
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/danielmunro/otto-community-service

