apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: infra
  description: Infrastructure repository
  tags:
    - yaml
    - k8s
  links:
    - url: https://github.com/third-place/infra
      title: Git Repository
spec:
  type: service
  lifecycle: production
  owner: dev-team
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka
  description: Kafka
spec:
  type: kafka
  lifecycle: production
  owner: dev-team
  dependencyOf:
    - api:user-service
    - api:community-service
    - api:image-service
    - api:notification-service
