version: "3"
services:
  user_service:
    image: ghcr.io/third-place/user-service:v0.1.6
    ports:
      - "8080:8080"
    env_file:
      - .env/user-service
    depends_on:
      - db
  community_service:
    image: ghcr.io/third-place/community-service:v0.1.9-1
    ports:
      - "8081:8081"
    env_file:
      - .env/community-service
    depends_on:
      - db
      - user_service
  image_service:
    image: ghcr.io/third-place/image-service:v0.1.3-1
    ports:
      - "8082:8082"
    env_file:
      - .env/image-service
    depends_on:
      - db
      - user_service
  notification_service:
    image: ghcr.io/third-place/notification-service:v0.1.9
    ports:
      - "8083:8083"
    env_file:
      - .env/notification-service
    depends_on:
      - db
      - user_service
  db:
    hostname: db
    image: "postgres"
    env_file:
      - .env/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./bin/postgres:/docker-entrypoint-initdb.d
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "users:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper