---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: backstage
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/third-place/backstage

