---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ui
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: ui
  targetNamespace: default

