apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: users
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: images
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: posts
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: post-likes
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: replies
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: follows
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
